import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import reportsRouter from "./reports";
import conversationsRouter from "./conversations";
import dashboardRouter from "./dashboard";
import companyProfilesRouter from "./company-profiles";
import researchRouter from "./research";
import workflowsRouter from "./workflows";
import storageRouter from "./storage";
import documentsRouter from "./documents";
import orgRouter from "./org";
import auditRouter from "./audit";
import analyticsRouter from "./analytics";
import vaultRouter from "./vault";
import integrationsRouter from "./integrations";
import workflowDefinitionsRouter from "./workflow-definitions";
import workflowExecutionsRouter from "./workflow-executions";
import humanReviewsRouter from "./human-reviews";
import vaultQueryRouter from "./vault-query";
import savedQueriesRouter from "./saved-queries";
import sharingRouter from "./sharing";
import commentsRouter from "./comments";
import activityRouter from "./activity";
import playbooksRouter from "./playbooks";
import adsRouter from "./ads";
import connectorsRouter from "./connectors";
import scrapeRouter from "./scrape";
import seoRouter from "./seo";
import pipedreamWorkflowsRouter from "./pipedream-workflows";
import boardsRouter from "./boards";
import notebooksRouter from "./notebooks";
import contextHealthRouter from "./context-health";
import intelligenceRouter from "./intelligence";
import intelligenceInsightsRouter from "./intelligence-insights";
import exportsRouter from "./exports";
import contextDefinitionsRouter from "./context-definitions";
import notificationsRouter from "./notifications";
import mcpRouter from "./mcp";
import agentMemoryRouter from "./agent-memory";
import scheduledQueriesApiRouter from "./scheduled-queries";
import genericWebhooksRouter from "./generic-webhooks";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(reportsRouter);
router.use(conversationsRouter);
router.use(dashboardRouter);
router.use(companyProfilesRouter);
router.use(researchRouter);
router.use(workflowsRouter);
router.use(storageRouter);
router.use(documentsRouter);
router.use(orgRouter);
router.use(auditRouter);
router.use(analyticsRouter);
router.use(vaultRouter);
router.use(integrationsRouter);
router.use(workflowDefinitionsRouter);
router.use(workflowExecutionsRouter);
router.use(humanReviewsRouter);
router.use(vaultQueryRouter);
router.use(savedQueriesRouter);
router.use(sharingRouter);
router.use(commentsRouter);
router.use(activityRouter);
router.use(playbooksRouter);
router.use(adsRouter);
router.use(connectorsRouter);
router.use(scrapeRouter);
router.use(seoRouter);
router.use(pipedreamWorkflowsRouter);
router.use(boardsRouter);
router.use(notebooksRouter);
router.use(contextHealthRouter);
router.use(intelligenceRouter);
router.use(intelligenceInsightsRouter);
router.use(exportsRouter);
router.use(contextDefinitionsRouter);
router.use(notificationsRouter);
router.use(mcpRouter);
router.use(agentMemoryRouter);
router.use(scheduledQueriesApiRouter);
router.use(genericWebhooksRouter);

export default router;
