export {
  SerpApiClient,
  SerpApiError,
  getSerpApiClient,
  type SerpApiOptions,
  type OrganicResult,
  type KnowledgeGraph,
  type RelatedQuestion,
  type AnswerBox,
  type GoogleSearchResult,
  type TrendTimelineItem,
  type RelatedTopic,
  type RelatedQuery,
  type GoogleTrendsResult,
  type NewsResult,
  type GoogleNewsResult,
  type ShoppingResult,
  type GoogleShoppingResult,
} from "./client";
